### ISSUE TITLE
Fresh Breakage 

### ISSUE THREAD

**Issue by n2j3** [socketubs/pyhn#31]
```
$ pyhn
Traceback (most recent call last):
  File "/usr/local/bin/pyhn", line 8, in <module>
    hn_gui.main()
  File "/usr/local/lib/python2.7/dist-packages/pyhn/gui.py", line 85, in main
    self.build_interface()
  File "/usr/local/lib/python2.7/dist-packages/pyhn/gui.py", line 124, in build_interface
    self.cache_manager.refresh()
  File "/usr/local/lib/python2.7/dist-packages/pyhn/cachemanager.py", line 44, in refresh
    stories = self.api.getTopStories(extra_page=self.extra_page)
  File "/usr/local/lib/python2.7/dist-packages/pyhn/hnapi.py", line 307, in getTopStories
    stories += self.getStories(source_latest)
  File "/usr/local/lib/python2.7/dist-packages/pyhn/hnapi.py", line 240, in getStories
    storyNumber = self.getStoryNumber(story)
  File "/usr/local/lib/python2.7/dist-packages/pyhn/hnapi.py", line 101, in getStoryNumber
    return int(source[numberStart:numberEnd])
ValueError: invalid literal for int() with base 10: '<span class="rank">1'
```

**Comment by socketubs** [comment]
`0.2.7` is on Pypi :smile: 
Just run `pip install -U pyhn`.

**Comment by n2j3** [comment]
odd.. i thought i had the latest version. Apologies for the commotion..

**Comment by socketubs** [comment]
Oh no do not apologize!
I just fix and push it there are 5 minutes :smile:
